### PR TITLE
make raw method robuster

### PR DESCRIPTION
**Pull request by xwa130**
overview
---
- [x] when one calls `raw(method, query)` with method undefined, it's supposed to return a rejected promise;
- [x] when one calls `raw(method, query)` with query method not a function, it's supposed to return a rejected promise; 
- [x] otherwise, it's supposed to return the correct result. 

issue 
---
When I `git clone`, `npm install` and `npm test`, it always fails. I don't figure out what happened there... 

version 
--- 
Since this is a minor change, I would suggest it as 0.4.1. @slajax @daffl Would you please take a look at this? Please let me if it has any problem. Thank you.

### CODE REVIEW

**Comment by jciolek** [comment]
Hi @xwa130, thanks for contributing!

I would like to ask you to add tests for the changes (and in general the erroneous scenarios). Also, the build seems to be failing.

Looking forward to the changes!

Cheers,
Jacek

**Comment by slajax** [comment]
@xwa130 I'll try to help you debug the failing tests tomorrow and then you can add the extra tests for this PR as per @jcolek's suggestion.

**Comment by xwa130** [comment]
@jciolek Thanks for your comment, it'll be great if you could give some clue for some reasons that it fails even if I start this repo from fresh, I would love to add more tests to make this repo robuster. 

@slajax Thank you for your help! 👍 as forever~

**Comment by slajax** [comment]
@xwa130 if you click the details of the failing tests above you can find the error. You can also see it in travis CI [here](https://travis-ci.org/feathersjs/feathers-elasticsearch/jobs/262387364#L1335-L1341). It looks to me like the way you refactored your code, isn't supported by one of the other tests. The error that is being thrown says:

```
  1) Elasticsearch Service Specific Elasticsearch tests raw() should show the mapping of index test:
     GeneralError: There is no query method indices
      at Error.GeneralError (node_modules/feathers-errors/lib/index.js:177:17)
      at errorHandler (src/index.js:32:4305)
      at runMicrotasksCallback (internal/process/next_tick.js:64:5)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

It gives you the line numbers, the test and the method, so you should be able to tweak that test to ensure that your tests coverage passes. You will also want to add tests that account for the way you have changed the arguments in your raw function. 

If that won't be possible, you can role back the changes and simply implement the change which returns an instance of a reject promise to resolve the original issue you found.

The additional changes are nice to have, but the unfortunately won't be accepted without test coverage, especially if the previously stable tests are now failing.

Once this is fixed up, let us know and we'll go about merging / tagging / releasing.

**Comment by xwa130** [comment]
@slajax @jciolek , tests all passed : )ready for merging

**Comment by daffl** [comment]
Thank you. Released as v0.4.2

**Pull request merged**
